language: node_js
node_js:
- 4.4.7
branches:
  only:
  - develop
  - master
install:
- npm install
- npm install -g gulp
script:
- gulp test
deploy:
  provider: script
  script: bin/deploy.sh
notifications:
  slack:
    secure: MoD2zHatGzxNadji7tgbKl13Q8Oq/0rjEW+gadHSxnOFsw8QkkpT6D2g4Q45UfQe6u116Rl4mSWhhtnSmb0UQ38mmorU6Yj2IjKtLak7Zj49G+6XnDHKnyqvtaF0EGkjUxtx5U8IKLsWZkW5kEIFwaTCd2AHvbC5BTLvYYKD9tI=
