language: node_js
node_js:
- 4.4.7
branches:
  only:
  - develop
  - master
install:
- npm install
- npm install -g gulp
- curl -sLO http://go-cli.s3-website-us-east-1.amazonaws.com/releases/v6.9.0/cf-linux-amd64.tgz
- tar -xf cf-linux-amd64.tgz
script:
- gulp test
- cf login -a api.ng.bluemix.net -u $bluemixID -p $bluemixPassword -o "CIO Lab iFundIT" -s "AgileTeamTool"
- curl -sLO $agileManifestURL
- curl -sLO $agileManifestGreenURL
- cf push agile-tool-nodejs-green-stage -f agile-team-tool-green-manifest.yml
- cf map-route agile-tool-nodejs-green-stage mybluemix.net --hostname agile-tool-nodejs-stage
- cf unmap-route agile-tool-nodejs-stage mybluemix.net --hostname agile-tool-nodejs-stage
- cf push agile-tool-nodejs-stage -f agile-team-tool-manifest.yml
- cf map-route agile-tool-nodejs-stage mybluemix.net --hostname agile-tool-nodejs-stage
- cf unmap-route agile-tool-nodejs-green-stage mybluemix.net --hostname agile-tool-nodejs-stage
- cf delete agile-tool-nodejs-green-stage -f
notifications:
  slack:
    secure: MoD2zHatGzxNadji7tgbKl13Q8Oq/0rjEW+gadHSxnOFsw8QkkpT6D2g4Q45UfQe6u116Rl4mSWhhtnSmb0UQ38mmorU6Yj2IjKtLak7Zj49G+6XnDHKnyqvtaF0EGkjUxtx5U8IKLsWZkW5kEIFwaTCd2AHvbC5BTLvYYKD9tI=
