language: node_js
node_js:
- 4.4.7
branches:
  only:
  - develop
  - master
install:
- npm install
- npm install -g gulp
script:
- gulp test
notifications:
  slack:
    secure: QARIdK8z/GhI/9Sij+pNZqNHQYe2XLdN2VMHNMtDn9f9Nhdrm64fr1IA4eObO1B3xcI+fs9Xllr8DntzK1xWchjFo+o0WQlfQH2BP/hhHMaZsKEB1kix4eZApnDIbEA8S7ZQuB8bruOUixWjWOG3OAr4UommTBjB8rQs+vBNOD4=
