language: node_js
sudo: required
node_js:
- 4.4.7
branches:
  only:
  - develop
  - master
before_install:
- gem update --system 1.8.30
install:
# Start our servers
- docker run -d --name redis -p 6379:6379 redis
- docker run -d --name mongo -p 27017:27017 mongo:3.2.8
- echo "deb http://repo.mongodb.org/apt/ubuntu trusty/mongodb-org/3.2 multiverse" | sudo tee /etc/apt/sources.list.d/mongodb-org-3.2.list
- sudo apt-get --allow-unauthenticated update
- sudo apt-get install -y --allow-unauthenticated mongodb-org-tools
- printf "@whitewater:registry=https://npm-registry.whitewater.ibm.com/\n//npm-registry.whitewater.ibm.com/:_authToken=${npmToken}\n@w3:registry=https://npm-registry.whitewater.ibm.com/" > .npmrc
- npm install
- npm install -g gulp
- chmod +x bin/deploy.sh
# Import test database
- curl -sL https://ibm.box.com/shared/static/qg39as43e5d8toa466l3ixyz0i2ttoyr.gz > agiletool_stage.tar.gz
- tar -xf agiletool_stage.tar.gz
- mongorestore -h localhost --port 27017 --db agiletool_stage agiletool_stage
script:
- npm run test
- gulp test
services:
- docker
deploy:
  provider: script
  script: echo "Deployment disabled"
  skip_cleanup: true
notifications:
  slack:
    secure: oFbgEM85HquK1FJXn8jl3HvxSrHgpR3C8GL+b3mYExw5cPpADFT1QvIP5b/d6tA0LsKEW6YFCPXZkqlEkUfjB1TSbXm+VsNoqwNvxyEGJD/drtCyvrNoRUEA7XFI1VeotXZz9aTGh2GXUuMmDd1568M+c0yrhqZU1BqJimQnegE=