language: node_js
node_js:
- 4.4.7
branches:
  only:
  - develop
  - master
install:
- npm install
- npm install -g gulp
- chmod +x bin/deploy.sh
script:
- gulp jshint
services:
- redis-server
deploy:
  provider: script
  script: bin/deploy.sh
  skip_cleanup: true
notifications:
  slack:
    secure: oFbgEM85HquK1FJXn8jl3HvxSrHgpR3C8GL+b3mYExw5cPpADFT1QvIP5b/d6tA0LsKEW6YFCPXZkqlEkUfjB1TSbXm+VsNoqwNvxyEGJD/drtCyvrNoRUEA7XFI1VeotXZz9aTGh2GXUuMmDd1568M+c0yrhqZU1BqJimQnegE=
