swagger: "2.0"
info:
  description: "This is a draft spec for returning a list of track and plan integrations that will be supported by Agile Team Tool for automated reporting purposes."
  version: "1.0.0"
  title: "Agile Team Tool Integrations"
host: "agiletool.mybluemix.net"
basePath: "/api"
tags:
- name: 'integrations'
  description: "Supported integrations by ATT"
schemes:
- "http"
paths:
  
  /integrations/tools:
    get:
      tags:
      - "Tools"
      summary: "Get list of integrations"
      description: "Retrieves a list of integrations and their supported servers"
      produces:
      - "application/json"
      responses:
        200:
          description: "successful"
          examples:
            application/json:
             tools:
               - toolId: RTC
                 toolName: Rational Team Concert (RTC)
                 servers:
                   - igartc01.swg.usma.ibm.com
                   - igartc02.swg.usma.ibm.com
                   - igartc03.swg.usma.ibm.com
    
                   
  /integrations/tool/{toolId}/server/{server}/projects:
    get:
      tags:
      - "Tools"
      parameters:
      - name: toolId
        in: path
        description: tool id passed in URI
        required: true
        type: string
        format: string
      - name: server
        in: path
        description: server passed in URI
        required: true
        type: string
        format: string  
      summary: "Get list of RTC project areas"
      description: "Retrieves a list of project areas within a given RTC server"
      produces:
      - "application/json"
      responses:
        200:
          description: "successful"
          examples:
            application/json:
               projects:
                - projectId: ''
                  projectName: ''
  /integrations/tool/{toolId}/server/{server}/project/{projectId}/types:
    get:
      tags:
      - "Tools"
      parameters:
      - name: toolId
        in: path
        description: tool id passed in URI
        required: true
        type: string
        format: string
      - name: server
        in: path
        description: server passed in URI
        required: true
        type: string
        format: string  
      - name: projectId
        in: path
        description: RTC project area id
        required: true
        type: string
        format: string    
      summary: "Get list of RTC work item types"
      description: "Retrieves a list of work item types within a given RTC project area"
      produces:
      - "application/json"
      responses:
        200:
          description: "successful"
          examples:
            application/json:
               projects:
                - projectId: ''
                  projectName: '' 
  /integrations/tool/{toolId}/server/{server}/project/{projectId}/states:
    get:
      tags:
      - "Tools"
      parameters:
      - name: toolId
        in: path
        description: tool id passed in URI
        required: true
        type: string
        format: string
      - name: server
        in: path
        description: server passed in URI
        required: true
        type: string
        format: string  
      - name: projectId
        in: path
        description: RTC project area id
        required: true
        type: string
        format: string    
      summary: "Get list of RTC work item states"
      description: "Retrieves a list of workflow states for work items within a given RTC project area"
      produces:
      - "application/json"
      responses:
        200:
          description: "successful"
          examples:
            application/json:
              
  /teams/{teamId}/integration:
    get:
      tags:
      - "Tools"
      parameters:
      - name: teamId
        in: path
        description: tool id passed in URI
        required: true
        type: string
        format: string
      summary: "Read the integration configuration details for my ATT team"
      description: ""
      produces:
      - "application/json"
      responses:
        200:
          description: "successful"
          examples:
            application/json:
               toolId: RTC
               server: igartc02...
               settings:
               projectId: ''
               defectWorkItemTypes:
                - com.ibm.rtc.Defect
                - Bug
               defectInProgressStates:
                - Started
                - Ready to Test
               defectResolvedStates:
                - Resolved
                - Verified
                - Done
               storyWorkItemTypes:
                - UserStory
                - Story
               storyPointsFieldId:
                - estimate
                - size
               storyInProgressStates:
                - In Progress
                - In Review
               storyResolvedStates:
                - Verified
                - Done
               iterationPattern: Sprint %
    post:
      tags:
      - "Tools"
      parameters:
      - name: teamId
        in: path
        description: tool id passed in URI
        required: true
        type: string
        format: string
      summary: "Save the integration configuration details for my ATT team"
      description: "Retrieves a list of workflow states for work items within a given RTC project area"
      produces:
      - "application/json"
      responses:
        200:
          description: "successful"
          examples:
            application/json:
               toolId: RTC
               server: igartc02...
               settings:
               projectId: ''
               defectWorkItemTypes:
                - com.ibm.rtc.Defect
                - Bug
               defectInProgressStates:
                - Started
                - Ready to Test
               defectResolvedStates:
                - Resolved
                - Verified
                - Done
               storyWorkItemTypes:
                - UserStory
                - Story
               storyPointsFieldId:
                - estimate
                - size
               storyInProgressStates:
                - In Progress
                - In Review
               storyResolvedStates:
                - Verified
                - Done
               iterationPattern: Sprint %           
  /teams/{teamId}/integration/preview:
    post:
      tags:
      - "Tools"
      parameters:
      - name: teamId
        in: path
        description: tool id passed in URI
        required: true
        type: string
        format: string
      summary: "Preview results of a configuration"
      description: "Show results of the metrics calculations for the given configuration. If the iteration pattern matches multiple iterations in the RTC project area, only process the most recently completed (max end date < today)"
      produces:
      - "application/json"
      responses:
        200:
          description: "successful"
          examples:
            application/json:
               velocity:
                - storyPointsCommitted: 5 
                - storyPointsDelivered: 2
               throughput:
                - storyCardsCommitted: 2
                - storyCardsDelivered: 1
               defects:
                - defectsStartBal: 0
                - defectsOpened: 0
                - defectsClosed: 0
                - defectsEndBal: 0
               deployments: []
               wip: 0
               backlog: 0